### ISSUE TITLE
Configuring the Server Base URL

### ISSUE THREAD

**Issue by qspweissen** [zammad/zammad-docker#25]
### Infos:

* Docker version: 18.03.1-ce
* Operating system (Docker host): Debian 9.4

### Expected behavior:

*
I would like to open zammad with the following base URL "example.com/zammad" because i want to use a reverse proxy with the proxy pass /zammad.
 

### Actual behavior:

*
It is not possible to use zammad with a prefix on my reverse proxy. Without a prefix i can see the zammad wizard to configure the system.

### Steps to reproduce the behavior:

*
A reverse proxy in front of the zammad-container with port 443.
Zammad-Container with port 80.
https://example-proxy.com/zammad > http://example-container.com/zammad (not working)
Apache Proxy Pass conf:
ProxyPass /zammad  http://example-container.com/zammad 
ProxyPassReverse /zammad   http://example-container.com/zammad 

https://example-proxy.com > http://example-container.com (working)

**Comment by monotek** [comment]
I dont think this is anything tzo do with teh container.
Not sure if it should work anyway.
@martini ?

**Comment by monotek** [comment]
ping

**Comment by MrGeneration** [comment]
Sorry didn't see this issue.
Sorry, but it's not possible to work via subdirectories at the moment.

This is, because the application has hardcoded stuff inside.

We will change this at some point in the future, but don't have a roadmap for this yet.
Sorry about that.

I'll be closing the issue for now.

**Comment by martini** [comment]
> I don't think this has anything to do with the container.
> Not sure if it should work anyway.

That's right. It's not related to the docker container.

It's related to some reverse proxy configuration and Zammad.

Anyway, it will not work because Zammad will not know about sub directories, so all generated links of Zammad would be wrong. Also the web app will not know about different sub urls for REST endpoints.

Summary:
1) Its not related to docker.
2) It will not work because Zammad will need the correct REST endpoints (URLs) to work correctly.
